lara_processes/urls.py
"""_____________________________________________________________________

:PROJECT: LARA

*lara_processes urls *

:details: lara_processes urls module.
         - add app specific urls here

:file:    views.py
:authors: mark doerr

:date: (creation)          20180627
:date: (last modification) 20190125

.. note:: -
.. todo:: - 
________________________________________________________________________
"""
__version__ = "0.0.2"

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from . import views

# Add your lara_processes urls here.

#~ urlpatterns = [
    #~ # path('', TemplateView.as_view(template_name='index.html'), name='lara_processes-main-view'),
    #~ # path('subdir/', include('.urls')),
#~ ]


app_name = 'lara_processes' # !! this sets the apps namespace to be used in the template

# the 'name' attribute is used in templates to address the url independant of the view
# it is used/called by the {% url %} template tag
urlpatterns = [
    path('', views.index, name='index'),   
    #~ path(r'^processlist$', views.processList, name='process_list'),
    #~ path(r'^(?P<process_id>[0-9]+)/$', views.processDetails, name='process_details'),
    path('search/', views.searchForm, name='searchForm'),
    path('search-results/', views.search, name='search'),
    path('results/', views.results, name='results'),
    path('generator/', 
        TemplateView.as_view(template_name='process_generator/index.html'),
        name='process-generator-index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lara_processes/templates/lara_processes/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

lara_processes/templates/lara_processes/index.html
{% extends "lara_base.html" %}

{% block title %}Process-Overview{% endblock %}

{% block top %} 
  <h1> LARA Processes</h1>
  <p> </p> 
{% endblock %}

{% block main_content %}
{% if lara_process_list %}
    <ul>
    {% for item in lara_process_list %}
       <li><a href="{% url 'lara_processes:device_details' item.device_id %}" title={{ item.device.name }}> {{ item.name }} {{ item.full_name }} </a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No processes are available.</p>
{% endif %}

{% endblock %}

lara_processes/templates/lara_processes/processList.html
{% extends "lara_processes_base.html" %}

{% block title %}Table-Table{% endblock %}

{% block top %} 
  <h1> LARA Device Table</h1>
  <p> </p> 
{% endblock %}

{% block main_content %}
{% if lara_device_list %}

   <table class="report">
   <caption>{{ table_caption }}</caption>
   <thead>
       <tr>
          <th rowspan=2 > Name </th> <th rowspan=2 > Full name </th> <th rowspan=2 > Warrenty </th>
       </tr>
   </thead> 
   <tbody>
    {% for item in lara_device_list %}
       <tr><td><a href="{% url 'lara_processes:device_details' item.device_id %}" title={{ item.full_name }}> {{ item.name }} </a> </td> <td> {{ item.full_name }} </td> <td> {{ item.end_of_warrenty_date }} </td> </tr>
    {% endfor %}
   </tbody>
   </table>
    
{% else %}
    <p>No devices are available.</p>
{% endif %}

{% endblock %}

lara_processes/templates/lara_processes/processes.html
{% extends "lara_processes_base.html" %}

{% load static %}

{% if lara_user %}

{% block title %} People detail {% endblock %}

{% block top %} 
  <h1> LARA People detail </h1>
  <p> LARA people detail   </p> 
  <div class='portrait-image' > 
        <a> <img style="width:110px" src="{% static "lara_people/"%}{{lara_user.entity.name}}/{{lara_user.entity.image_filename}}" alt="{{lara_user.entity.image_filename}}">
        </a>
  </div>
{% endblock %}

{% block main_content %}


<div class='info-box' > 
    <div class='info-box-main'>
         {{lara_user.user.first_name }} {{lara_user.user.last_name }} 
    </div>

    <div class='info-box-detail'>
         {{lara_user.entity.name }} 
    </div>

</div>

<div class='address-box'>
<h2> Address </h2>
    
    <div class='address-box-detail'>  
     <p>{{lara_user.entity.full_name }}  </p>
     <p> {{lara_user.entity.address.street }}</p>
     <p> {{lara_user.entity.address.postal_colde }}</p> 
     <p> {{lara_user.entity.address.city }} </p>
     </div>
</div>
 

{% endblock %}

{% else %}
    <p>Sorry, no Users available.</p>
{% endif %}

lara_processes/templates/lara_processes/results.html
{% extends "lara_processes_base.html" %}

{% block title %}people search res.{% endblock %}

{% block top %} 
  <h1> LARA People Search Results </h1>
  <p>  </p> 
{% endblock %}


{% block main_content %}
{% if lara_user_list %}
    <ul>
    {% for item in lara_user_list %}
       <li><a href="{% url 'lara_processes:lara_user_detail' item.lara_user_id %}" title={{ item.user.full_name }}> {{ item.user.first_name }} {{ item.user.last_name }} </a> </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No matching users found.</p>
{% endif %}

{% endblock %}

lara_processes/templates/lara_processes/search.html
{% extends "lara_processes_base.html" %}

{% block title %}Search People{% endblock %}

{% block top %} 
  <h1> Search LARA People </h1>
  <p>  </p> 
{% endblock %}


{% block main_content %}

<center>
  <form action="{% url 'lara_processes:search'   %}" method="post">
    {% csrf_token %}

    {# <label for="input_search">Search person:  </label> #}
    <input type="text" name="search" id="input_search" value="" />
    
    <input type="submit" value="Search" />
  </form>

</center>

{% endblock %}